[theme]
base = "dark"
primaryColor = "#0948af"
backgroundColor = "#0c521f"
secondaryBackgroundColor = "#225ab4"
textColor = "#FFFFFF"
font = " 'Aldrich' , 'Palestine': https://fonts.google.com/specimen/Aldrich & https://www.arfonts.net/palestine-font"
