[theme]
base = "dark"
primaryColor = "#3B82F6"
backgroundColor = "#0B0F19"
secondaryBackgroundColor = "#141C2E"
textColor = "#FFFFFF"
font = " 'Aldrich' , 'Palestine': https://fonts.google.com/specimen/Aldrich & https://www.arfonts.net/palestine-font"
